version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "pip"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
