bin/*                               usr/bin/
src/main.py                          usr/lib/csas-sharepoint/
test_result_loading.py               usr/lib/csas-sharepoint/
validate_report.py                   usr/lib/csas-sharepoint/
multiflexi/csas-sharepoint.app.json  usr/lib/multiflexi/apps/
README.md                           usr/share/doc/csas-sharepoint/
debian/man/csas-sharepoint.1         usr/share/man/man1/
